# Generated by Django 5.2.7 on 2025-10-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_initial'),
        ('financials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('cost_type', models.CharField(choices=[('Additive', 'Additive'), ('Subtractive', 'Subtractive'), ('Inclusive', 'Inclusive')], default='Inclusive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.paymentcategory')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.paymentmethod')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditure_requests_made', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_requests', to='Eapp.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
