# Generated by Django 5.2.7 on 2025-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_expenditurerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costbreakdown',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='costbreakdown',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='costbreakdown',
            name='status',
        ),
    ]
