# Generated by Django 5.2.7 on 2025-10-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_initial'),
        ('financials', '0004_remove_costbreakdown_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Eapp.task'),
        ),
    ]
