# Generated by Django 5.2.7 on 2025-10-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_payment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
