# Generated by Django 5.2.5 on 2025-08-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
