# Generated by Django 5.2.3 on 2025-09-02 08:12

import Eapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0004_alter_user_options_remove_user_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to=Eapp.models.user_profile_picture_path, verbose_name='Profile Picture'),
        ),
    ]
