# Generated by Django 5.2.7 on 2025-10-14 19:26

import Eapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Parts', 'Awaiting Parts'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Picked Up', 'Picked Up'), ('Terminated', 'Terminated')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('Full', 'Full'), ('Not Full', 'Not Full'), ('Motherboard Only', 'Motherboard Only')], default='Full', max_length=20)),
                ('device_notes', models.TextField(blank=True)),
                ('laptop_model', models.CharField(max_length=100)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20)),
                ('current_location', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('Yupo', 'Yupo'), ('Katoka kidogo', 'Katoka kidogo'), ('Kaacha', 'Kaacha'), ('Expedited', 'Expedited'), ('Ina Haraka', 'Ina Haraka')], default='Yupo', max_length=20)),
                ('date_in', models.DateField(default=Eapp.models.get_current_date)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('is_debt', models.BooleanField(default=False)),
                ('is_referred', models.BooleanField(default=False)),
                ('workshop_status', models.CharField(blank=True, choices=[('In Workshop', 'In Workshop'), ('Solved', 'Solved'), ('Not Solved', 'Not Solved')], max_length=20, null=True)),
                ('workshop_sent_at', models.DateTimeField(blank=True, null=True)),
                ('workshop_returned_at', models.DateTimeField(blank=True, null=True)),
                ('original_location', models.CharField(blank=True, max_length=100, null=True)),
                ('qc_notes', models.TextField(blank=True, null=True)),
                ('qc_rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('picked_up', 'Picked Up'), ('device_note', 'Device Note')], max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Task Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
