# Generated by Django 5.2.7 on 2025-10-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='serial_number',
        ),
    ]
