# Generated by Django 5.2.3 on 2025-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_task_payment_taskactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Parts', 'Awaiting Parts'), ('Completed', 'Completed'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
