# Generated by Django 5.2.7 on 2025-10-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_alter_task_created_at_alter_task_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
