# Generated by Django 5.0.7 on 2025-09-13 20:09

import Eapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=Eapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_in',
            field=models.DateField(default=Eapp.models.get_current_date),
        ),
    ]
