# Generated by Django 5.0.7 on 2025-09-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0006_location_alter_payment_date_alter_task_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
