# Generated by Django 5.0.7 on 2025-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0008_brand_remove_task_laptop_make_task_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='device_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='device_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Not Full', 'Not Full'), ('Motherboard Only', 'Motherboard Only')], default='Full', max_length=20),
        ),
    ]
