# Generated by Django 5.0.7 on 2025-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0009_task_device_notes_task_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='commissioned_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='is_commissioned',
            field=models.BooleanField(default=False),
        ),
    ]
