# Generated by Django 5.0.7 on 2025-09-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0010_task_commissioned_by_task_is_commissioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='serial_number',
            field=models.CharField(blank=True, default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Parts', 'Awaiting Parts'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Terminated', 'Terminated')], default='Pending', max_length=20),
        ),
    ]
