# Generated by Django 5.0.7 on 2025-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0011_alter_task_serial_number_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_workshop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_workshop',
            field=models.BooleanField(default=False, verbose_name='Workshop'),
        ),
    ]
