# Generated by Django 5.0.7 on 2025-09-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0012_location_is_workshop_user_is_workshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborationRequest',
        ),
    ]
