# Generated by Django 5.0.7 on 2025-09-19 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0013_delete_collaborationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_to_workshop_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='workshop_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_tasks', to='Eapp.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='workshop_status',
            field=models.CharField(blank=True, choices=[('In Workshop', 'In Workshop'), ('Solved', 'Solved'), ('Not Solved', 'Not Solved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='workshop_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
