# Generated by Django 5.0.7 on 2025-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0014_task_original_technician_task_workshop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workshop_returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='workshop_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
