# Generated by Django 5.0.7 on 2025-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0015_task_workshop_returned_at_task_workshop_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop')], max_length=20),
        ),
    ]
