# Generated by Django 5.0.7 on 2025-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0016_alter_taskactivity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
