# Generated by Django 5.0.7 on 2025-09-22 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0017_task_original_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approved_date',
        ),
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
