# Generated by Django 5.0.7 on 2025-09-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0018_remove_task_approved_date_task_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sent_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_out_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
