# Generated by Django 5.0.7 on 2025-09-23 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0019_task_sent_out_by_alter_task_date_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qc_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
