# Generated by Django 5.0.7 on 2025-09-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0020_task_qc_notes_task_qc_rejected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='customer_phone',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Parts', 'Awaiting Parts'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Picked Up', 'Picked Up'), ('Terminated', 'Terminated')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Eapp.customer'),
            preserve_default=False,
        ),
    ]
