# Generated by Django 5.0.7 on 2025-09-27 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0021_customer_remove_task_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_cost',
        ),
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_type', models.CharField(choices=[('Additive', 'Additive'), ('Subtractive', 'Subtractive'), ('Inclusive', 'Inclusive')], default='Inclusive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdowns', to='Eapp.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
