# Generated by Django 5.0.7 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0022_remove_task_total_cost_costbreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='category',
            field=models.CharField(default='Inclusive', max_length=100),
        ),
    ]
