# Generated by Django 5.0.7 on 2025-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0023_costbreakdown_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='urgency',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Yupo', 'Yupo'), ('Katoka kidogo', 'Katoka kidogo'), ('Kaacha', 'Kaacha'), ('Expedited', 'Expedited'), ('Ina Haraka', 'Ina Haraka')], default='Yupo', max_length=20),
        ),
    ]
