# Generated by Django 5.0.7 on 2025-10-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0024_remove_task_urgency_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='urgency',
        ),
    ]
