# Generated by Django 5.0.7 on 2025-10-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0025_rename_priority_task_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Repairman', 'Repairman')], default='Normal', max_length=20, verbose_name='Customer Type'),
        ),
    ]
