# Generated by Django 5.0.7 on 2025-10-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0026_customer_customer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_commissioned',
            new_name='is_referred',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='commissioned_by',
            new_name='referred_by',
        ),
    ]
