# Generated by Django 5.0.7 on 2025-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0028_referrer_alter_task_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop'), ('rejected', 'Rejected'), ('returned', 'Returned')], max_length=20),
        ),
    ]
