# Generated by Django 5.0.7 on 2025-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0030_alter_taskactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('picked_up', 'Picked Up'), ('device_note', 'Device Note')], max_length=20),
        ),
    ]
