# Generated by Django 5.0.7 on 2025-10-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0031_alter_taskactivity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Front Desk', 'Front Desk'), ('Technician', 'Technician'), ('Accountant', 'Accountant')], max_length=20, verbose_name='Role'),
        ),
    ]
