# Generated by Django 5.0.7 on 2025-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0033_paymentmethod_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
