# Generated by Django 5.2.7 on 2025-10-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0034_task_is_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
    ]
