# Generated by Django 5.2.7 on 2025-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0035_remove_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costbreakdown',
            name='category',
        ),
        migrations.AddField(
            model_name='costbreakdown',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
