# Generated by Django 5.2.7 on 2025-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0036_remove_costbreakdown_category_costbreakdown_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='category',
            field=models.CharField(default='Inclusive', max_length=100),
        ),
    ]
