# Generated by Django 5.2.7 on 2025-10-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0038_costbreakdown_approved_by_costbreakdown_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costbreakdown',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Eapp.paymentmethod'),
        ),
    ]
