# Generated by Django 5.2.7 on 2025-10-09 11:50

from django.db import migrations

def create_refund_payment_method(apps, schema_editor):
    PaymentMethod = apps.get_model('Eapp', 'PaymentMethod')
    PaymentMethod.objects.get_or_create(name='Refund', defaults={'is_user_selectable': False})

def reverse_create_refund_payment_method(apps, schema_editor):
    PaymentMethod = apps.get_model('Eapp', 'PaymentMethod')
    PaymentMethod.objects.filter(name='Refund').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0039_costbreakdown_payment_method'),
    ]

    operations = [
        migrations.RunPython(create_refund_payment_method, reverse_create_refund_payment_method),
    ]