# Generated by Django 5.2.7 on 2025-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0040_auto_20251009_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_user_selectable',
            field=models.BooleanField(default=True),
        ),
    ]
