# Generated by Django 5.2.7 on 2025-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0042_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='Customer Payment', max_length=255),
        ),
    ]
